services:
  app:
    image: ghcr.io/lunarcatowo/tba-scout:main
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=${Port:-5000}
      - TBA_API_KEY=${TBA_API_KEY}
    ports:
      - "${Port:-5000}:${Port:-5000}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${Port:-5000}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.scope=tba-scout"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup --rolling-restart --scope tba-scout --label-enable
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=300